spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:59267/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=HXdGRDppGdRaemGPJRlbPeHCzJPqJwpD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8084
